server:
  port: ${PORT:8080}
  hostname: localhost
spring:
  application:
    name: calculator
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  mvc:
    servlet:
      path: /systemair-ac
    static-path-pattern: /statico/**
  datasource:
     name: 'systemairac'
     url: jdbc:${DATABASE_PATH:mysql://localhost:3306/systemairac?serverTimezone=UTC}
     username: ${DATABASE_USER:root}
     password: ${DATABASE_PASSWORD:Nbirf}
  flyway:
    baseline-on-migrate: true
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:${DATABASE_PATH:postgresql://localhost:5432/db_calculator}
#    username: ${DATABASE_USER:postgres}
#    password: ${DATABASE_PASSWORD:123456}
#    driver-class-name: org.postgresql.Driver


management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
logging:
  level:
    org.springframework.web: DEBUG








